INSERT INTO tb_user (name, email, password) VALUES('cida', 'cida@gmail.com', '123456');
INSERT INTO tb_user (name, email, password) VALUES('josé', 'jo@gmail.com', '123456');

INSERT INTO tb_genero(nome) VALUES('Comédia');
INSERT INTO tb_genero(nome) VALUES('Drama');
INSERT INTO tb_genero(nome) VALUES('Ação');

INSERT INTO tb_filme(titulo, ano, genero_id) VALUES('Corra', 2000, 3);
INSERT INTO tb_filme(titulo, ano, genero_id) VALUES('Minha mãe é uma peça', 2012, 1);
INSERT INTO tb_filme(titulo, ano, genero_id) VALUES('Titanic', 2005, 2);

INSERT INTO tb_review(texto, filme_id, user_id ) VALUES('Muito bom', 1, 1);
INSERT INTO tb_review(texto, filme_id, user_id ) VALUES('Engraçado', 2, 2);
--
-- create table tb_filme (
--        ano integer,
--        genero_id bigint not null,
--        id bigint generated by default as identity,
--        titulo varchar(255),
--        primary key (id)
--    )

--Hibernate:
--    create table tb_review (
--        filme_id bigint not null,
--        id bigint generated by default as identity,
--        user_id bigint not null,
--        texto TEXT,
--        primary key (id)
--    )
--Hibernate:
--    alter table if exists tb_filme
--       add constraint FKc2g6ur42quxknaoux8a9g8mfu
--       foreign key (genero_id)
--       references tb_genero
--Hibernate:
--    alter table if exists tb_review
--       add constraint FK3uwtt3m9g0dd3gx4xbh5mhgli
--       foreign key (filme_id)
--       references tb_filme
--Hibernate:
--    alter table if exists tb_review
--       add constraint FKqeh83gbufxg1ft0ubwn7w0tty
--       foreign key (user_id)
--       references tb_user